=== +++<font color="green">+++集合处理：+++</font>+++

. 【强制】关于``hashCode``和``equals``的处理，遵循如下规则： +
&emsp;1） 只要覆写equals，就必须覆写hashCode。 +
&emsp;2） 因为Set存储的是不重复的对象，依据hashCode和equals进行判断，所以Set存储的对象必须覆写这两个方法。 +
&emsp;3） 如果自定义对象作为Map的键，那么必须覆写hashCode和equals。

. 【强制】使用Map的方法``keySet()``/`values()`/``entrySet()``返回集合对象时，不可以对其进行添加元素操作，否则会抛出UnsupportedOperationException异常。

. 【强制】在使用``java.util.stream.Collectors``类的``toMap()``方法转为``Map``集合时，一定要使用含有参数类型为``BinaryOperator``，参数名为``mergeFunction``的方法，否则当出现相同key值时会抛出IllegalStateException异常。
+
+++<font color="#977C00">+++说明：+++</font>+++参数mergeFunction的作用是当出现key重复时，自定义对value的处理策略。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    List<Pair<String, Double>> pairArrayList = new ArrayList<>(3);
    pairArrayList.add(new Pair<>("version", 6.19));
    pairArrayList.add(new Pair<>("version", 10.24));
    pairArrayList.add(new Pair<>("version", 13.14));
    Map<String, Double> map = pairArrayList.stream().collect(
    // 生成的map集合中只有一个键值对：{version=13.14}
    Collectors.toMap(Pair::getKey, Pair::getValue, (v1, v2) -> v2));
----
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    String[] departments = new String[] {"iERP", "iERP", "EIBU"};
    // 抛出IllegalStateException异常
    Map<Integer, String> map = Arrays.stream(departments)
        .collect(Collectors.toMap(String::hashCode, str -> str));
----

. 【强制】在使用``java.util.stream.Collectors``类的``toMap()``方法转为``Map``集合时，一定要注意当``value``为``null``时会抛NPE异常。
+
+++<font color="#977C00">+++说明：+++</font>+++在java.util.HashMap的merge方法里会进行如下的判断：
+
[,java]
----
    if (value == null || remappingFunction == null)
    throw new NullPointerException();
----
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    List<Pair<String, Double>> pairArrayList = new ArrayList<>(2);
    pairArrayList.add(new Pair<>("version1", 4.22));
    pairArrayList.add(new Pair<>("version2", null));
    Map<String, Double> map = pairArrayList.stream().collect(
    // 抛出NullPointerException异常
    Collectors.toMap(Pair::getKey, Pair::getValue, (v1, v2) -> v2));
----

. 【强制】判断所有集合内部的元素是否为空，使用isEmpty()方法，而不是size()==0的方式。
+
+++<font color="#977C00">+++说明：+++</font>+++在某些集合中，前者的时间复杂度为O(1)，而且可读性更好。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    Map<String, Object> map = new HashMap<>(16);
    if(map.isEmpty()) {
        System.out.println("no element in this map.");
    }
----

. 【强制】Collections类返回的对象，如：`emptyList()`/``singletonList()``等都是immutable list，不可对其进行添加或者删除元素的操作。
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
某二方库的方法中，如果查询无结果，返回Collections.emptyList()空集合对象，调用方一旦进行了添加元素的操作，就会触发UnsupportedOperationException异常。

. 【强制】ArrayList的subList结果不可强转成ArrayList，否则会抛出ClassCastException异常：java.util.RandomAccessSubList cannot be cast to java.util.ArrayList;
+
+++<font color="#977C00">+++说明：+++</font>+++subList()返回的是ArrayList的内部类SubList，并不是 ArrayList本身，而是ArrayList 的一个视图，对于SubList的所有操作最终会反映到原列表上。

. 【强制】在subList场景中，+++<font color="#0033CC">+++高度注意+++</font>+++对父集合元素的增加或删除，均会导致子列表的遍历、增加、删除产生ConcurrentModificationException 异常。

. 【强制】使用集合转数组的方法，必须使用集合的toArray(T[] array)，传入的是类型完全一致、长度为0的空数组。
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
直接使用toArray无参方法存在问题，此方法返回值只能是Object[]类，若强转其它类型数组将出现ClassCastException错误。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    List<String> list = new ArrayList<>(2);
    list.add("guan");
    list.add("bao");

    array = list.toArray(new String[0]);
----
+
+++<font color="#977C00">+++说明：+++</font>+++使用toArray带参方法，数组空间大小的length： +
 1）+++<font color="#0033CC">+++等于0+++</font>+++，动态创建与size相同的数组，性能最好。 +
 2）+++<font color="#0033CC">+++大于0但小于size+++</font>+++，重新创建大小等于size的数组，增加GC负担。 +
 3）+++<font color="#0033CC">+++等于size+++</font>+++，在高并发情况下，数组创建完成之后，size正在变大的情况下，负面影响与2相同。 +
 4）+++<font color="#0033CC">+++大于size+++</font>+++，空间浪费，且在size处插入null值，存在NPE隐患。

. 【强制】在使用Collection接口任何实现类的addAll()方法时，都要对输入的集合参数进行NPE判断。
+
+++<font color="#977C00">+++说明：+++</font>+++在ArrayList#addAll方法的第一行代码即``Object[] a = c.toArray();`` 其中c为输入集合参数，如果为null，则直接抛出异常。

. 【强制】使用工具类Arrays.asList()把数组转换成集合时，不能使用其修改集合相关的方法，它的add/remove/clear方法会抛出UnsupportedOperationException异常。
+
+++<font color="#977C00">+++说明：+++</font>+++asList的返回对象是一个Arrays内部类，并没有实现集合的修改方法。Arrays.asList体现的是适配器模式，只是转换接口，后台的数据仍是数组。
String[] str = new String[] { "a", "b" };
List+++<String>+++list = Arrays.asList(str); 第一种情况：list.add("c"); 运行时异常。 第二种情况：str[0]= "changed"; 那么list.get(0)也会随之修改，反之亦然。+++</String>+++

. 【强制】泛型通配符<? extends T>来接收返回的数据，此写法的泛型集合不能使用add方法，而<? super T>不能使用get方法，两者在接口调用赋值的场景中易出错。
+
+++<font color="#977C00">+++说明：+++</font>+++扩展说一下PECS (Producer Extends Consumer Super)原则：第一、频繁往外读取内容的，适合用<? extends T>。第二、经常往里插入的，适合用<? super T>。

. 【强制】在无泛型限制定义的集合赋值给泛型限制的集合时，在使用集合元素时，需要进行instanceof判断，避免抛出ClassCastException异常。
+
+++<font color="#977C00">+++说明：+++</font>+++毕竟泛型是在JDK5之后才出现，考虑到向前兼容，编译器是允许非泛型集合与泛型集合互相赋值。
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    List<String> generics = null;
    List notGenerics = new ArrayList(10);
    notGenerics.add(new Object());
    notGenerics.add(new Integer(1));

    generics = notGenerics;
    // 此处抛出ClassCastException异常
    String string = generics.get(0);
----

. 【强制】不要在foreach循环里进行元素的remove/add操作。remove元素请使用Iterator方式，如果并发操作，需要对Iterator迭代器对象加锁。
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    List<String> list = new ArrayList<>();
    list.add("targetItem");
    list.add("other");

    for (String item : list) {
        if ("targetItem".equals(item)) {
            list.remove(item);
        }
    }
----
+
+++<font color="#977C00">+++说明：+++</font>+++上述代码的执行结果肯定会出乎大家的意料，那么试一下把"`1`"换成"`2`"，会是同样的结果吗？
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    Iterator<String> iterator = list.iterator();
    while (iterator.hasNext()) {
        String item = iterator.next();
        if (删除元素的条件) {
            iterator.remove();
        }
    }
----

. 【强制】在JDK7版本以上，Comparator要满足如下三个条件，不然Arrays.sort，Collections.sort会抛IllegalArgumentException异常。
+   
+++<font color="#977C00">+++说明：+++</font>+++ +
1） x，y的比较结果和y，x的比较结果相反。 +
2） x>y，y>z，则x>z。 +
3） x=y，则x，z比较结果和y，z比较结果相同。
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
下例中没有处理相等的情况，交换两个对象判断结果并不互反，不符合第一个条件，在实际使用中可能会出现异常。
+
[,java]
----
    new Comparator<Student>() {
        @Override
        public int compare(Student o1, Student o2) {
            return o1.getId() > o2.getId() ? 1 : -1;
        }
    }
----

. 【推荐】泛型集合使用时，在JDK7版本及以上，使用 diamond 语法或全省略。
+
+++<font color="#977C00">+++说明：+++</font>+++菱形泛型，即 diamond，直接使用<>来指代前边已经指定的类型。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    // <> diamond 方式
    HashMap<String, String> userCache = new HashMap<>(16);

    // 全省略方式
    ArrayList<User> users = new ArrayList(10);
----

. 【推荐】集合初始化时，指定集合初始值大小。
+
+++<font color="#977C00">+++说明：+++</font>+++HashMap使用如下构造方法进行初始化，如果暂时无法确定集合大小，那么指定默认值（16）即可：
+
[,java]
----
    public HashMap(int initialCapacity) {
        this(initialCapacity, DEFAULT_LOAD_FACTOR);
    }
----
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
HashMap需要放置1024个元素，由于没有设置容量初始大小，随着元素增加而被迫不断扩容，resize()方法总共会调用8次，反复重建哈希表和数据迁移。当放置的集合元素个数达千万级时会影响程序性能。

. 【推荐】使用entrySet遍历Map类集合KV，而不是keySet方式进行遍历。
+
+++<font color="#977C00">+++说明：+++</font>+++keySet其实是遍历了2次，一次是转为Iterator对象，另一次是从hashMap中取出key所对应的value。而entrySet只是遍历了一次就把key和value都放到了entry中，效率更高。如果是JDK8，使用Map.forEach方法。
+
+++<font color="#019858">+++正例：+++</font>+++
+
values()返回的是V值集合，是一个List集合对象；keySet()返回的是K值集合，是一个Set集合对象；entrySet()返回的是K-V值组合集合。

. 【推荐】高度注意Map类集合K/V能不能存储null值的情况，如下表格：
+
|===
| 集合类 | Key | Value | Super | 说明

| Hashtable
| +++<font color="#FF4500">+++不允许为null+++</font>+++
| +++<font color="#FF4500">+++不允许为null+++</font>+++
| Dictionary
| 线程安全

| ConcurrentHashMap
| +++<font color="#FF4500">+++不允许为null+++</font>+++
| +++<font color="#FF4500">+++不允许为null+++</font>+++
| AbstractMap
| 锁分段技术（JDK8:CAS)

| TreeMap
| +++<font color="red">+++不允许为null+++</font>+++
| +++<font color="#0033CC">+++允许为null+++</font>+++
| AbstractMap
| 线程不安全

| HashMap
| +++<font color="#0033CC">+++允许为null+++</font>+++
| +++<font color="#0033CC">+++允许为null+++</font>+++
| AbstractMap
| 线程不安全
|===

. 【参考】合理利用好集合的有序性(sort)和稳定性(order)，避免集合的无序性(unsort)和不稳定性(unorder)带来的负面影响。
+
+++<font color="#977C00">+++说明：+++</font>+++有序性是指遍历的结果是按某种比较规则依次排列的。稳定性指集合每次遍历的元素次序是一定的。如：ArrayList是order/unsort；HashMap是unorder/unsort；TreeSet是order/sort。

. 【参考】利用Set元素唯一的特性，可以快速对另一个集合进行去重操作，避免使用List的contains()进行遍历去重或者判断包含操作。
