=== +++<font color="green">+++格式规约：+++</font>+++

. 【强制】如果是大括号内为空，则简洁地写成{}即可，大括号中间无需换行和空格；如果是非空代码块则： +
&emsp;1） 左大括号前不换行。 +
&emsp;2） 左大括号后换行。 +
&emsp;3） 右大括号前换行。 +
&emsp;4） 右大括号后还有else等代码则不换行；表示终止右大括号后必须换行。
. 【强制】左小括号和右边相邻字符之间不出现空格；右小括号和左边相邻字符之间也不出现空格；而左大括号前需要加空格。详见第5条下方正例提示。
. 【强制】if/for/while/switch/do等保留字与左右括号之间都必须加空格。
. 【强制】任何二目、三目运算符的左右两边都必须加一个空格。
+
+++<font color="#977C00">+++说明：+++</font>+++包括赋值运算符=、逻辑运算符&&、加减乘除符号等。

. 【强制】采用4个空格缩进，禁止使用tab字符。
+
+++<font color="#977C00">+++说明：+++</font>+++如果使用tab缩进，必须设置1个tab为4个空格。IDEA设置tab为4个空格时，请勿勾选：`Use tab character`；而在eclipse中，必须勾选``insert spaces for tabs``。
+
+++<font color="#019858">+++正例：+++</font>+++（涉及1-5点）
+

[,java]
----
    public static void main(String[] args) {
        // 缩进4个空格
        String say = "hello";
        // 运算符的左右必须有一个空格
        int flag = 0;
        // 关键词if与括号之间必须有一个空格，括号内f与左括号，0与右括号不需要空格
        if (flag == 0) {
            System.out.println(say);
        }

        // 左大括号前加空格且不换行；左大括号后换行
        if (flag == 1) {
            System.out.println("world");
        // 右大括号前换行，右大括号后有else，不用换行
        } else {
            System.out.println("ok");
        // 在右大括号后直接结束，则必须换行
        }
    }
----

. 【强制】注释的双斜线与注释内容之间+++<font color="#0033CC">+++有且仅有+++</font>+++一个空格。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    // 这是示例注释，请注意在双斜线之后有一个空格
    String commentString = new String();
----

. 【强制】在进行类型强制转换时，右括号与被强制转换的值之间不需要任何空格隔开。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    long first = 1000000000000L;
    int second = (int)first + 2;
----

. 【强制】单行字符数不超过120个，超出则需要换行，换行时遵循如下原则： +
&emsp;1） 第二行相对第一行缩进4个空格，从第三行开始，不再继续缩进，参考示例。 +
&emsp;2） 运算符与下文一起换行。 +
&emsp;3） 方法调用的点符号与下文一起换行。 +
&emsp;4） 方法调用中的多个参数需要换行时，在逗号后进行。    +
&emsp;5） 在括号前不要换行，见反例。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    StringBuilder sb = new StringBuilder();
    // 超过120个字符的情况下，换行缩进4个空格，并且方法前的点号一起换行
    sb.append("zi").append("xin")...
        .append("huang")...
        .append("huang")...
        .append("huang");
----
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    StringBuilder sb = new StringBuilder();
    // 超过120个字符的情况下，不要在括号前换行
    sb.append("zi").append("xin")...append
        ("huang");

    // 参数很多的方法调用可能超过120个字符，逗号后才是换行处
    invoke(args1, args2, args3, ...
        , argsX);
----

. 【强制】方法参数在定义和传入时，多个参数逗号后边必须加空格。
+
+++<font color="#019858">+++正例：+++</font>+++下例中实参的+++<font color="#0033CC">+++args1,+++</font>+++后边必须要有一个空格。
+
[,java]
----
    method(args1, args2, args3);
----

. 【强制】IDE的text file encoding设置为UTF-8; IDE中文件的换行符使用Unix格式，不要使用windows格式。
. 【推荐】没有必要增加若干空格来使变量的赋值等号与上一行对应位置的等号对齐。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    int one = 1;
    long two = 2L;
    float three = 3F;
    StringBuilder sb = new StringBuilder();
----
+
+++<font color="#977C00">+++说明：+++</font>+++
+
增加sb这个变量，如果需要对齐，则给one、two、three都要增加几个空格，在变量比较多的情况下，是非常累赘的事情。

. 【推荐】单个方法的总行数不超过80行。
+
+++<font color="#977C00">+++说明：+++</font>+++除注释之外的方法签名、左右大括号、方法内代码、空行、回车及任何不可见字符的总行数不超过80行。
+
+++<font color="#019858">+++正例：+++</font>+++代码逻辑分清红花和绿叶，个性和共性，绿叶逻辑单独出来成为额外方法，使主干代码更加清晰；共性逻辑抽取成为共性方法，便于复用和维护。

. 【推荐】不同逻辑、不同语义、不同业务的代码之间插入一个空行分隔开来以提升可读性。
+
+++<font color="#977C00">+++说明：+++</font>+++任何情形，没有必要插入+++<font color="#0033CC">+++多个空行+++</font>+++进行隔开。