:pp: {plus}{plus}

=== +++<font color="green">+++并发处理：+++</font>+++

. 【强制】获取单例对象需要保证线程安全，其中的方法也要保证线程安全。+++<font color="#977C00">
+
+++说明：+++</font>+++资源驱动类、工具类、单例工厂类都需要注意。

. 【强制】创建线程或线程池时请指定有意义的线程名称，方便出错时回溯。
+
+++<font color="#019858">+++正例：+++</font>+++
+
自定义线程工厂，并且根据外部特征进行分组，比如：来自同一机房的调用，把机房编号赋值给whatFeaturOfGroup
+
[,java]
----
    public class UserThreadFactory implements ThreadFactory {

        private final String namePrefix;
        private final AtomicInteger nextId = new AtomicInteger(1);

        // 定义线程组名称，在jstack问题排查时，非常有帮助
        UserThreadFactory(String whatFeaturOfGroup) {
            namePrefix = "From UserThreadFactory's " + whatFeaturOfGroup + "-Worker-";
        }

        @Override
        public Thread newThread(Runnable task) {
            String name = namePrefix + nextId.getAndIncrement();
            Thread thread = new Thread(null, task, name, 0, false);
            System.out.println(thread.getName());
            return thread;
        }
    }
----

. 【强制】线程资源必须通过线程池提供，不允许在应用中自行显式创建线程。
+
+++<font color="#977C00">+++说明：+++</font>+++使用线程池的好处是减少在创建和销毁线程上所消耗的时间以及系统资源的开销，解决资源不足的问题。如果不使用线程池，有可能造成系统创建大量同类线程而导致消耗完内存或者"`过度切换`"的问题。

. 【强制】线程池不允许使用Executors去创建，而是通过ThreadPoolExecutor的方式，这样的处理方式让写的同学更加明确线程池的运行规则，规避资源耗尽的风险。
+
+++<font color="#977C00">+++说明：+++</font>+++Executors返回的线程池对象的弊端如下： +
&emsp;&emsp;1）``FixedThreadPool``和``SingleThreadPool``: +
&emsp;&emsp;&emsp;&emsp;允许的请求队列长度为Integer.MAX_VALUE，可能会堆积大量的请求，从而导致OOM。 +
&emsp;&emsp;2）`CachedThreadPool`: +
&emsp;&emsp;&emsp;&emsp;允许的创建线程数量为Integer.MAX_VALUE，可能会创建大量的线程，从而导致OOM。

. 【强制】SimpleDateFormat 是线程不安全的类，一般不要定义为static变量，如果定义为static，必须加锁，或者使用DateUtils工具类。
+
+++<font color="#019858">+++正例：+++</font>+++
+
注意线程安全，使用DateUtils。亦推荐如下处理：
+
[,java]
----
    private static final ThreadLocal<DateFormat> df = new ThreadLocal<DateFormat>() {
        @Override
        protected DateFormat initialValue() {
            return new SimpleDateFormat("yyyy-MM-dd");
        }
    };
----
+
+++<font color="#977C00">+++说明：+++</font>+++如果是JDK8的应用，可以使用Instant代替Date，LocalDateTime代替Calendar，DateTimeFormatter代替SimpleDateFormat，官方给出的解释：simple beautiful strong immutable thread-safe。

. 【强制】必须回收自定义的``ThreadLocal``变量，尤其在线程池场景下，线程经常会被复用，如果不清理自定义的 ``ThreadLocal``变量，可能会影响后续业务逻辑和造成内存泄露等问题。尽量在代码中使用try-finally块进行回收。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    objectThreadLocal.set(userInfo);
    try {
        ...
    } finally {
        objectThreadLocal.remove();
    }
----

. 【强制】高并发时，同步调用应该去考量锁的性能损耗。能用无锁数据结构，就不要用锁；能锁区块，就不要锁整个方法体；能用对象锁，就不要用类锁。
+
+++<font color="#977C00">+++说明：+++</font>+++尽可能使加锁的代码块工作量尽可能的小，避免在锁代码块中调用RPC方法。

. 【强制】对多个资源、数据库表、对象同时加锁时，需要保持一致的加锁顺序，否则可能会造成死锁。
+
+++<font color="#977C00">+++说明：+++</font>+++线程一需要对表A、B、C依次全部加锁后才可以进行更新操作，那么线程二的加锁顺序也必须是A、B、C，否则可能出现死锁。

. 【强制】在使用阻塞等待获取锁的方式中，必须在try代码块之外，并且在加锁方法与try代码块之间没有任何可能抛出异常的方法调用，避免加锁成功后，在finally中无法解锁。
+
+++<font color="#977C00">+++说明一：+++</font>+++如果在lock方法与try代码块之间的方法调用抛出异常，那么无法解锁，造成其它线程无法成功获取锁。
+
+++<font color="#977C00">+++说明二：+++</font>+++如果lock方法在try代码块之内，可能由于其它方法抛出异常，导致在finally代码块中，unlock对未加锁的对象解锁，它会调用AQS的tryRelease方法（取决于具体实现类），抛出IllegalMonitorStateException异常。
+
+++<font color="#977C00">+++说明三：+++</font>+++在Lock对象的lock方法实现中可能抛出unchecked异常，产生的后果与说明二相同。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    Lock lock = new XxxLock();
    // ...
    lock.lock();
    try {
        doSomething();
        doOthers();
    } finally {
        lock.unlock();
    }
----
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    Lock lock = new XxxLock();
    // ...
    try {
        // 如果此处抛出异常，则直接执行finally代码块
        doSomething();
        // 无论加锁是否成功，finally代码块都会执行
        lock.lock();
        doOthers();

    } finally {
        lock.unlock();
    }
----

. 【强制】在使用尝试机制来获取锁的方式中，进入业务代码块之前，必须先判断当前线程是否持有锁。锁的释放规则与锁的阻塞等待方式相同。
+
+++<font color="#977C00">+++说明：+++</font>+++Lock对象的unlock方法在执行时，它会调用AQS的tryRelease方法（取决于具体实现类），如果当前线程不持有锁，则抛出IllegalMonitorStateException异常。
+
+++<font color="#019858">+++正例：+++</font>+++
+
[,java]
----
    Lock lock = new XxxLock();
    // ...
    boolean isLocked = lock.tryLock();
    if (isLocked) {
        try {
            doSomething();
            doOthers();
        } finally {
            lock.unlock();
        }
    }
----

. 【强制】并发修改同一记录时，避免更新丢失，要么在应用层加锁，要么在缓存加锁，要么在数据库层使用乐观锁，使用version作为更新依据。
+
+++<font color="#977C00">+++说明：+++</font>+++如果每次访问冲突概率小于20%，推荐使用乐观锁，否则使用悲观锁。乐观锁的重试次数不得小于3次。
+
+++<font color="#019858">+++正例：+++</font>+++
+
集团很多业务使用TairManager方法：incr(namespace, lockKey, 1, 0, expireTime); 判断返回步长是否为1，实现分布式锁。

. 【强制】多线程并行处理定时任务时，Timer运行多个TimeTask时，只要其中之一没有捕获抛出的异常，其它任务便会自动终止运行，使用ScheduledExecutorService则没有这个问题。

. 【推荐】资金相关的金融敏感信息，使用悲观锁策略。
+
+++<font color="#977C00">+++说明：+++</font>+++乐观锁在获得锁的同时已经完成了更新操作，校验逻辑容易出现漏洞，另外，乐观锁对冲突的解决策略有较复杂的要求，处理不当容易造成系统压力或数据异常，所以资金相关的金融敏感信息不建议使用乐观锁更新。
+
+++<font color="#019858">+++正例：+++</font>+++
+
悲观锁遵循+++<font color="#0033CC">+++一锁二判三更新四释放+++</font>+++的原则。

. 【推荐】使用CountDownLatch进行异步转同步操作，每个线程退出前必须调用countDown方法，线程执行代码注意catch异常，确保countDown方法被执行到，避免主线程无法执行至await方法，直到超时才返回结果。
+
+++<font color="#977C00">+++说明：+++</font>+++注意，子线程抛出异常堆栈，不能在主线程try-catch到。

. 【推荐】避免Random实例被多线程使用，虽然共享该实例是线程安全的，但会因竞争同一seed 导致的性能下降。
+
+++<font color="#977C00">+++说明：+++</font>+++Random实例包括java.util.Random 的实例或者 Math.random()的方式。
+
+++<font color="#019858">+++正例：+++</font>+++
+
在JDK7版本及以上，可以直接使用API ThreadLocalRandom；而在JDK7前，需要编码保证每个线程持有一个单独的Random实例。

. 【推荐】通过双重检查锁（double-checked locking）实现延迟初始化需要将目标属性声明为 volatile型（比如修改helper的属性声明为``private volatile Helper helper = null;``）；
+
+++<font color="#FF4500">+++反例：+++</font>+++
+
[,java]
----
    public class LazyInitDemo {
        private Helper helper = null;

        public Helper getHelper() {
            if (helper == null) {
                synchronized (this) {
                    if (helper == null) {
                        helper = new Helper();
                    }
                }
            }
            return helper;
        }
        // other methods and fields...
    }
----

. 【参考】volatile解决多线程内存不可见问题。对于一写多读，是可以解决变量同步问题，但是如果多写，同样无法解决线程安全问题。如果想取回count{pp}数据，使用如下类实现：AtomicInteger count = new AtomicInteger(); count.addAndGet(1); 参考内存模型： http://www.infoq.com/cn/articles/java-memory-model-1?utm_source=infoq&utm_medium=related_content_link&utm_campaign=relatedContent_articles_clk[深入理解java内存模型]。　　
+
+++<font color="#977C00">+++说明：+++</font>+++count{pp}操作如果是JDK8，推荐使用LongAdder对象，比AtomicLong性能更好（减少乐观锁的重试次数）。

. 【参考】HashMap在容量不够进行resize时由于高并发可能出现死链，导致CPU飙升，在开发过程中注意规避此风险。

. 【参考】ThreadLocal对象使用static修饰，ThreadLocal无法解决共享对象的更新问题。
+
+++<font color="#977C00">+++说明：+++</font>+++这个变量是针对一个线程内所有操作共享的，所以设置为静态变量，所有此类实例共享此静态变量 ，也就是说在类第一次被使用时装载，只分配一块存储空间，所有此类的对象(只要是这个线程内定义的)都可以操控这个变量。
